### ISSUE TITLE
Unrecognized effect "?"

### ISSUE THREAD

**Issue by covingto** [covingto/pancanmafmerge#4]
@ckandoth might need your input on this one:

2016-04-01 00:36:53,319 - merge - INFO - Processing conversion of merges/BLCA/104c8e20-1b29-4d77-9633-359a35be48fb_01_10/tmp/merged.annotated.vcf -> merges/BLCA/104c8e20-1b29-4d77-9633-359a35be48fb_01_10/merged.maf
ERROR: Unrecognized effect "?". Please update your hashes!
Traceback (most recent call last):
  File "/stornext/snfs2/can/users/covingto/mcc-merge/scripts/merge.py", line 289, in <module>
    main(args)
  File "/stornext/snfs2/can/users/covingto/mcc-merge/scripts/merge.py", line 270, in main
    convert(args.OUTPUTMAF, annotated)
  File "/stornext/snfs2/can/users/covingto/mcc-merge/scripts/merge.py", line 243, in convert
    shell = True)
  File "/hgsc_software/python/python-2/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/hgsc_software/perl/perl-5.16.2/bin/perl /stornext/snfs2/can/users/covingto/mcc-merge/scripts/vcf2maf/vcf2maf.pl -no-annotate -input-vcf merges/BLCA/104c8e20-1b29-4d77-9633-359a35be48fb_01_10/tmp/merged.annotated.vcf -output-maf merges/BLCA/104c8e20-1b29-4d77-9633-359a35be48fb_01_10/tmpfile.vcf -vcf-tumor-id PRIMARY -vcf-normal-id NORMAL -tumor-id TCGA-DK-AA6U-01A-11D-A391-08 -normal-id TCGA-DK-AA6U-10A-01D-A394-08 -copythrough COSMIC,CENTERS,CONTEXT,DBVS' returned non-zero exit status 22

Can't put all of the info for privacy reasons but it really has '?' as the consequence: ATTGC|?|...  It's a PInDel complex variant

Propose to set '?' as lowest priority...

**Comment by ckandoth** [comment]
I'm not able to reproduce this error. But my first hunch is to use a newer version of Perl. VEP has problems with 5.18 and older. You're using 5.16.2. I was able to successfully annotate the following VCF with vcf2maf 1.6.6 and perl 5.22.

```
vcfs/BLCA/104c8e20-1b29-4d77-9633-359a35be48fb_01_10/C500.TCGA-DK-AA6U-01A-11D-A391-08.1.pindel.somatic.tcga_filtered.reheadered.vcf
```

**Comment by covingto** [comment]
could switch over to perl 5.18.2, would that require re-running the entire set or would the errors be isolated to just these cases?
I guess I would have to annotate the same file with both and diff them...

**Comment by covingto** [comment]
just to clarify, the annotation was successful, it was the conversion to maf.  Do you have any variants with ? as the consequence.  ATTGC should be relatively unique as an alt for that file.

**Comment by ckandoth** [comment]
All my consequences look legit. If you saw `ATTGC|?|` in the post-annotation VCF, then it was a direct output of VEP, that vcf2maf parsed and complained about. VEP does the weirdest things on older Perl versions. I've had the weirdest problems... so I wouldn't trust anything that comes out of VEP with 5.16.2. Sorry, but you likely need to rerun vcf2maf on other VCFs as well.

**Comment by covingto** [comment]
OK, will kill what I have and restart with perl 5.18.2

**Comment by covingto** [comment]
switching over to newer perl does not seem to work, not finding the right modules and running install with 5.18.2 also having problems.  According to ensemble (http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html) the only place that a version is mentioned is in the Windows install and they recommend 5.14 so there should be no issue with version number.  Reverting back to 5.16.2 and will update the hash conversion in vcf2maf

**Comment by ckandoth** [comment]
Here's the Perl version related problems I was describing - http://lists.ensembl.org/pipermail/dev/2016-January/011624.html and http://lists.ensembl.org/pipermail/dev/2014-October/010492.html. Here's everything you need to set up Perl 5.22 - https://gist.github.com/ckandoth/c16b9a423b54dc0a7a37 - including handling dependences for VEP. The important bit is that BioPerl is up to date.

**Comment by ckandoth** [comment]
Can you also send me the exact line in your VCF that causes this error, before you pass it into vcf2maf? I know you've done some transforms to the VCF... so I want to make sure to rule that out.
